name: 'Unity Runner-20.3.12f1'
author: Paul Pacheco <paulpach@gmail.com>
description: 'Run unity in batch mode'
inputs: 
  args:
    required: true
    description: 'Arguments to pass to unity'
  workdir:
    required: false
    default: ''
    description: 'working directory'

  solution:
    description: "Project solution,  typically"
    required: false
    default: 'workspace.sln'
  testCommand:
    description: "Command to invoke tests"
    required: false
  projectKey:
    description: "Specifies the key of the analyzed project in SonarQube"
    required: true
  projectName:
    description: "Specifies the name of the analyzed project in SonarQube"
    required: true
  sonarHostname:
    description: "The server URL"
    default: "https://sonarcloud.io"
    required: false
  sonarOrganisation:
    description: "Organisation"
    required: true
  beginArguments:
    description: "Arguments to append to the begin command"
    required: false
  endArguments:
    description: "Arguments to append to the end command"
    required: false
    
outputs:
  filePath:
    description: 'Path of the manual activation file'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'box'
  color: 'gray-dark'
